baseurl                  = "https://example.com"           # Your domain name
languageCode             = "en-us"
defaultContentLanguage   = "en"
isMultilingual           = false
title                    = "Jordan White"
theme                    = "sam"
pygmentsStyle            = "monokai"                        # https://help.farbox.com/pygments.html
pygmentsCodefences       = true
# googleAnalytics        = ""                               # Tracking code, eg. "UA-111111111-1"

[params]
    dateform             = "Mon Jan 02, 2006"
    dateformfull         = "Mon Jan 2 2006 15:04:05 EST"
    favicon              = "jordan.ico"
    homepage             = "Home"                           # What to call the home page link, link will not be rendered if empty
    footerText           = "Theme by Victoria Drake. All photos by Vivien Jester."


# Metadata for Open Graph and Twitter
    description          = "Jordan White, musician, guitarist, improviser, live-coder, composer"               # Max 160 characters show in search results
    title                = "Jordan White"
    # rss                = ""


[[params.mainMenu]]
    link = "about"
    text = "About"

[[params.mainMenu]]
    link = "music"
    text = "Music"

#[[params.mainMenu]]
 #   link = "teaching"
  #  text = "Teaching"

[[params.mainMenu]]
    link = "contact"
    text = "Contact"

[imaging]
    quality = 100
